# Basic Python Collections
http://people.duke.edu/~ccc14/sta-663-2017/01_Introduction_To_Python.html

## List methods

### Append

In [1]:
l = [1,2,3]
l

[1, 2, 3]

In [2]:
l.append(['a', 'b'])
l

[1, 2, 3, ['a', 'b']]

## Extend

In [3]:
l.extend(['a', 'b'])
l

[1, 2, 3, ['a', 'b'], 'a', 'b']

In [4]:
l + [4, 5]

[1, 2, 3, ['a', 'b'], 'a', 'b', 4, 5]

## Dictionaries

In [5]:
d = {1: 'a', 2:'b'}

In [6]:
for i in d.values():
    print(i)

a
b


In [7]:
for k,v in d.items():
    print(k, v)

1 a
2 b


In [8]:
d['something']

KeyError: 'something'

## Default Dictionaries

In [9]:
from collections import defaultdict

In [10]:
dd = defaultdict(lambda: 'yogesh')

In [11]:
dd['something']

'yogesh'

In [12]:
data = {
    'yogesh': 'blue',
    'linnea': 'red',
    'jared': 'blue',
    'jess': 'blue'
}

In [13]:
aggregate_dict = defaultdict(list)

In [14]:
for k, v in data.items():
    aggregate_dict[v].append(k)
aggregate_dict 

defaultdict(list, {'blue': ['yogesh', 'jared', 'jess'], 'red': ['linnea']})

In [15]:
dummy = {}
for k, v in data.items():
    if v not in dummy:
        dummy[v] = []
    dummy[v].append(k)
dummy

{'blue': ['yogesh', 'jared', 'jess'], 'red': ['linnea']}

In [16]:
iterable = [1,2,3] # (1,2,3) '123' {1,2,3} {1:'a', 2:'b', 3:'c'} range(0,3,1)

In [17]:
out = []
for item in iterable:
    if item > 2:
        break
    out.append(item)
out

[1, 2]

## Functions and Lambdas

In [18]:
def foo(x):
    return x*x

In [19]:
foo(10)

100

In [20]:
fool = lambda x: x*x

In [21]:
fool(10)

100

# Numpy arrays
https://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html

In [22]:
import numpy as np

In [23]:
py_array_like = (1.0,2,3)

In [24]:
np_array = np.array(py_array_like)

In [25]:
np_array

array([1., 2., 3.])

In [26]:
np_array.shape

(3,)

In [27]:
np_array.dtype

dtype('float64')

In [28]:
py_matrix_like = [[1,2,3],[1,2,3],[1,2,3]]

In [29]:
np_matrix = np.array(py_matrix_like)

In [30]:
np_matrix

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [31]:
np_matrix.shape

(3, 3)

# Matrix Operations

### Addition/Subtraction

In [32]:
np_matrix - 1

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [33]:
np_array + np_array

array([2., 4., 6.])

### Scalar Multiplcation

In [34]:
np_array * 0.5

array([0.5, 1. , 1.5])

### Matrix Multiplication

In [35]:
np.matmul(np_matrix, np_array)

array([14., 14., 14.])

In [36]:
np_matrix @ np_array

array([14., 14., 14.])

### Indexing

In [37]:
np_matrix[1:3,:]

array([[1, 2, 3],
       [1, 2, 3]])

# Random shuffling
https://docs.scipy.org/doc/numpy-1.14.0/reference/routines.random.html

In [38]:
# set the seed for numpy's random number generator
np.random.seed(1)

In [39]:
a = [1,2,3,4,5]

In [40]:
np.random.shuffle(a)
a

[3, 2, 5, 1, 4]

In [41]:
# remove the seed for numpy's random number generator
np.random.seed(None)

In [42]:
np.random.shuffle(a)
a

[1, 3, 4, 2, 5]

# Date and Time

In [43]:
import datetime

In [44]:
'test_%s.txt' % datetime.datetime.now()

'test_2019-08-26 16:27:20.382480.txt'

In [45]:
with open('test_%s.txt' % datetime.datetime.now(), 'w') as out_file:
    out_file.write('Hello, World!')